project:
  title: "Clarifying Correlation and Causation"
  type: website

  preview: 
    port: 3333
    browser: true
    watch-inputs: false
    navigate: true

  render:
    # Render all .qmd files
    - "**/*.qmd"

    # Don't render anything in the manuscript folder because that's handled separately with {targets}
    - "!manuscript/"
  resources:
    - "manuscript/output"
    # - "example_data.zip"

date-format: long

website:
  navbar:
    background: "#5F4690"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: "Methods"
        menu:
          - methods/observational.qmd
          - methods/rct.qmd
          - methods/diff-in-diff.qmd
          - methods/rdd.qmd
          - methods/iv.qmd
    right:
      - icon: github
        href: "https://github.com/andrewheiss/corrupt-caterpillar"
        aria-label: GitHub

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} 2024 by [Andrew Heiss](https://www.andrewheiss.com/) and Meng Ye<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/andrewheiss/corrupt-caterpillar)

format:
  html:
    theme:
      - zephyr
      - html/custom.scss
    toc: false
