project:
  output-dir: output
  preview: 
    port: 4444

  render: 
    - "manuscript.qmd"

language: 
  title-block-published: Latest version
  related-formats-title: Other formats
  other-links-title: Other links

csl: csl/apa.csl

# This is necessary to keep intermediate files/folders hanging around when 
# rendering to the same output format (like two different PDFs)
# https://github.com/quarto-dev/quarto-cli/issues/8373#issuecomment-1979245883
keep-md: true

format:
  wordcount-html: 
    output-file: index.html
    wordcount-banner: false

    toc: true
    shift-heading-level-by: 1
    theme: 
      - zephyr
      - html/custom.scss
    title-block-banner: "#000D51"
    include-in-header:
      - text: |
          <style type="text/css">
          h2.hide {
            display: none;
          }
          </style>

    lightbox: auto

    format-links:
      - html
      - format: hikmah-pdf
        text: PDF
        icon: file-pdf
      - format: hikmah-manuscript-pdf+ms
        text: Manuscripty PDF
        icon: file-pdf

    other-links:
      - text: GitHub repository
        href: https://github.com/andrewheiss/corrupt-caterpillar/
        icon: github
      # - text: SocArXiv preprint
      #   href: https://doi.org/10.31235/osf.io/9gmhp
      #   icon: link-45deg
      # - text: OSF project
      #   href: https://doi.org/10.17605/OSF.IO/R97Y3
      #   icon: link-45deg

    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300

  # Nice PDF output
  hikmah-pdf:
    output-file: heiss-ye-causation.pdf
    # Custom fonts
    mainfont: "Linux Libertine O"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    sansfont: "Inter"
    # mathfont: "Libertinus Math"
    linestretch: 1.05

    include-in-header:
      # The \everydisplay thing makes all math blocks use \small font
      text: |
        \usepackage{mathtools}
        \everydisplay\expandafter{\the\everydisplay\small}

        \makeatletter
        \@ifpackageloaded{unicode-math}{
        % Save mathtools' brackets
        \let\normalunderbracket=\underbracket
        \let\normaloverbracket=\overbracket
        }{}
        \makeatother

        % Add a little bit of extra space above minipages 
        % for gt table footnotes
        \usepackage{etoolbox}
        \AtBeginEnvironment{minipage}{\vspace{\baselineskip}}

    knitr:
      opts_chunk:
        dev: "cairo_pdf"


  # Manuscript-y PDF output
  hikmah-manuscript-pdf+ms:
    output-file: heiss-ye-causation-thing.pdf
    left-aligned: true
    endnotes: false

    # Custom fonts
    mainfont: "Linux Libertine O"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    # mathfont: "Libertinus Math"

    include-in-header:
      # The \everydisplay thing makes all math blocks use \small font
      text: |
        \usepackage{mathtools}
        \everydisplay\expandafter{\the\everydisplay\small }

        \makeatletter
        \@ifpackageloaded{unicode-math}{
        % Save mathtools' brackets
        \let\normalunderbracket=\underbracket
        \let\normaloverbracket=\overbracket
        }{}
        \makeatother

        % Add a little bit of extra space above minipages 
        % for gt table footnotes
        \usepackage{etoolbox}
        \AtBeginEnvironment{minipage}{\vspace{\baselineskip}}

    knitr:
      opts_chunk:
        dev: "cairo_pdf"
